_BASE_: [
  'coco_detection.yml',
  'runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetr_r50vd.yml',
  '_base_/rtdetr_reader.yml',
]

weights: /home/jjf/Desktop/RT-DETR/rtdetr_paddle/output/Final_instance_Label_Modify_Model/rtdetr_r50vd_6x_coco/best_model
find_unused_parameters: True
log_iter: 200