task: detection

num_classes: 1
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ../rtdetr_paddle/datasets/fracture_dataset/train/
    ann_file: ../rtdetr_paddle/datasets/fracture_dataset/annotations/semantic_bbox_train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 8
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ../rtdetr_paddle/datasets/fracture_dataset/val/
    ann_file: ../rtdetr_paddle/datasets/fracture_dataset/annotations/semantic_bbox_val.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False


test_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ../rtdetr_paddle/datasets/fracture_dataset/test/
    ann_file: ../rtdetr_paddle/datasets/fracture_dataset/annotations/semantic_bbox_test.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 8
  num_workers: 4
  drop_last: False