_BASE_: [
  '../datasets/coco_detection2.yml',
  '../runtime2.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetr_r50vd.yml',
  '_base_/rtdetr_reader.yml',
]

weights: /home/RT-DETR/rtdetr_paddle/output/xray/fold2/instance_20_drr_buu_pretrain/rtdetr_r50vd_6x_coco/best_model
find_unused_parameters: True # 多卡设置False
log_iter: 200
