_BASE_: [
  '../datasets/coco_detection4.yml',
  '../runtime4.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetr_r50vd.yml',
  '_base_/rtdetr_reader.yml',
]

weights: output/xray/fold4/semantic_drr_buu_pretrain_retrain/rtdetr_r50vd_6x_coco/best_model
find_unused_parameters: True # 多卡设置False
log_iter: 200
