_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_6x.yml',
  '_base_/rtdetr_r50vd.yml',
  '_base_/rtdetr_reader.yml',
]

weights: output/fracture_dataset/rtdetr_r50vd_6x_coco/best_model
find_unused_parameters: True # 多卡设置False
log_iter: 200
