metric: COCO
num_classes: 9

TrainDataset:
  name: COCODataSet
  image_dir: images3/train_20
  anno_path: annotations3/train_instance_20.json
  dataset_dir: /home/RT-DETR/rtdetr_paddle/datasets/miccai/xray
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: images3/val
  anno_path: annotations3/val_instance.json
  dataset_dir: /home/RT-DETR/rtdetr_paddle/datasets/miccai/xray
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations3/val_instance.json # also support txt (like VOC's label_list.txt)
  dataset_dir: /home/RT-DETR/rtdetr_paddle/datasets/miccai/xray # if set, anno_path will be 'dataset_dir/anno_path'