metric: COCO
num_classes: 4

TrainDataset:
  name: COCODataSet
  image_dir: images1/train_20
  anno_path: annotations1/train_semantic_20.json
  dataset_dir: datasets/miccai/xray
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: images1/train_60
  anno_path: annotations1/train_semantic_60.json
  dataset_dir: datasets/miccai/xray
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations1/train_semantic_60.json # also support txt (like VOC's label_list.txt)
  dataset_dir: datasets/miccai/xray # if set, anno_path will be 'dataset_dir/anno_path'
